version: '2'

services:
  web:
    build: ./web/
    ports:
     - "80:80"
    links:
     - db
  db:
    build: ./db/
    volumes:
    #- /tmp/mysqltmp:/var/lib/mysql
    - ./db/data:/docker-entrypoint-initdb.d
    environment:
     - MYSQL_ROOT_PASSWORD=passroot
     - MYSQL_DATABASE=dbname
